"""
Simple script to restore data from a backup database to the dev database.
This script:
1. Finds tables that exist in both databases
2. Finds columns that exist in both for each table
3. Copies data with ON CONFLICT DO NOTHING
4. Temporarily disables FK constraints during copy

Usage:
    python restore_from_backup.py [backup_db_name]
    
    If backup_db_name is not provided, it will use: photo_app_db_backup_1765827434
"""

import os
import sys
import json
import psycopg2
from psycopg2.extras import execute_values, Json
from psycopg2 import sql
from psycopg2 import errors as psycopg2_errors
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Database configuration
DB_HOST = os.getenv('DB_HOST', 'localhost')
DB_PORT = os.getenv('DB_PORT', '5432')
DB_USER = os.getenv('DB_USER', 'postgres')
DB_PASSWORD = os.getenv('DB_PASSWORD', '')
DB_NAME = os.getenv('DB_NAME', 'photo_app_db')

def get_postgres_conn(database):
    """Get PostgreSQL connection."""
    return psycopg2.connect(
        host=DB_HOST,
        port=DB_PORT,
        user=DB_USER,
        password=DB_PASSWORD,
        database=database
    )

def get_tables(conn):
    """Get list of tables in the database."""
    with conn.cursor() as cursor:
        cursor.execute("""
            SELECT table_name 
            FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_type = 'BASE TABLE'
            ORDER BY table_name
        """)
        return [row[0] for row in cursor.fetchall()]

def get_columns(conn, table_name):
    """Get list of columns for a table, ordered by ordinal_position."""
    with conn.cursor() as cursor:
        cursor.execute("""
            SELECT column_name, data_type
            FROM information_schema.columns 
            WHERE table_schema = 'public' 
            AND table_name = %s 
            ORDER BY ordinal_position
        """, (table_name,))
        return [(row[0], row[1]) for row in cursor.fetchall()]

def get_primary_key(conn, table_name):
    """Get primary key column(s) for a table."""
    with conn.cursor() as cursor:
        cursor.execute("""
            SELECT a.attname
            FROM pg_index i
            JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
            WHERE i.indrelid = %s::regclass
            AND i.indisprimary
            ORDER BY a.attnum
        """, (table_name,))
        return [row[0] for row in cursor.fetchall()]

def get_identity_columns(conn, table_name):
    """Get identity column(s) for a table (GENERATED ALWAYS or GENERATED BY DEFAULT)."""
    with conn.cursor() as cursor:
        cursor.execute("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = 'public'
            AND table_name = %s
            AND is_identity = 'YES'
        """, (table_name,))
        return [row[0] for row in cursor.fetchall()]

def copy_table_data(backup_conn, target_conn, table_name, common_columns):
    """Copy data from backup table to target table."""
    if not common_columns:
        return 0
    
    column_names = [col[0] for col in common_columns]
    
    # Check if table has primary key for ON CONFLICT
    pk_columns = get_primary_key(target_conn, table_name)
    has_pk = len(pk_columns) > 0 and all(pk in column_names for pk in pk_columns)
    
    # Build column list for SQL (quoted identifiers)
    columns_str = ', '.join([f'"{col}"' for col in column_names])
    table_str = f'"{table_name}"'
    
    # Build SELECT query for backup database
    select_query = f'SELECT {columns_str} FROM {table_str}'
    
    # Detect JSONB columns
    jsonb_column_indices = set()
    for i, (col_name, col_type) in enumerate(common_columns):
        if col_type in ('json', 'jsonb'):
            jsonb_column_indices.add(i)
    
    # Fetch data from backup
    with backup_conn.cursor() as backup_cursor:
        backup_cursor.execute(select_query)
        rows = backup_cursor.fetchall()
    
    if not rows:
        return 0
    
    # Convert JSONB columns to Json objects
    converted_rows = []
    for row in rows:
        converted_row = list(row)
        for i in jsonb_column_indices:
            value = converted_row[i]
            if value is not None:
                if isinstance(value, (dict, list)):
                    converted_row[i] = Json(value)
                elif isinstance(value, str):
                    # Try to parse as JSON string
                    try:
                        parsed = json.loads(value)
                        converted_row[i] = Json(parsed)
                    except (json.JSONDecodeError, TypeError):
                        # Not valid JSON, but it's a JSONB column - wrap as string JSON
                        converted_row[i] = Json(value)
                elif isinstance(value, (int, float, bool)):
                    # JSONB can store primitives directly
                    converted_row[i] = Json(value)
        converted_rows.append(tuple(converted_row))
    
    rows = converted_rows
    
    # Check if this table has an identity column that needs OVERRIDING SYSTEM VALUE
    identity_cols = get_identity_columns(target_conn, table_name)
    # Check if any identity column is in the columns we're inserting
    needs_override = any(identity_col in column_names for identity_col in identity_cols)
    
    # Build INSERT query as string (for execute_values compatibility)
    columns_str = ', '.join([f'"{col}"' for col in column_names])
    table_str = f'"{table_name}"'
    
    if has_pk:
        # Use ON CONFLICT DO NOTHING for tables with primary key
        if needs_override:
            insert_sql_str = f"""
                INSERT INTO {table_str} ({columns_str}) 
                OVERRIDING SYSTEM VALUE
                VALUES %s 
                ON CONFLICT DO NOTHING
            """
        else:
            insert_sql_str = f"""
                INSERT INTO {table_str} ({columns_str}) 
                VALUES %s 
                ON CONFLICT DO NOTHING
            """
    else:
        # For tables without primary key, try to insert and catch errors
        if needs_override:
            insert_sql_str = f"""
                INSERT INTO {table_str} ({columns_str}) 
                OVERRIDING SYSTEM VALUE
                VALUES %s
            """
        else:
            insert_sql_str = f"""
                INSERT INTO {table_str} ({columns_str}) 
                VALUES %s
            """
    
    # Insert data into target
    
    rows_inserted = 0
    with target_conn.cursor() as target_cursor:
        if has_pk:
            # Use execute_values for batch insert with conflict handling
            execute_values(target_cursor, insert_sql_str, rows, page_size=1000)
            rows_inserted = target_cursor.rowcount
        else:
            # For tables without primary key, try to insert all rows
            # If there are unique constraints, we'll catch errors
            try:
                execute_values(target_cursor, insert_sql_str, rows, page_size=1000)
                rows_inserted = target_cursor.rowcount
            except (psycopg2_errors.IntegrityError, psycopg2_errors.UniqueViolation):
                # If batch insert fails, try row by row
                for row in rows:
                    try:
                        target_cursor.execute(insert_sql_str, row)
                        rows_inserted += 1
                    except (psycopg2_errors.IntegrityError, psycopg2_errors.UniqueViolation):
                        # Skip duplicates/conflicts
                        continue
    
    return rows_inserted

def main():
    """Restore data from backup database to dev database."""
    # Default backup database name
    default_backup_db = 'photo_app_db_backup_1765827434'
    
    # Get backup database name from command line or use default
    if len(sys.argv) > 1:
        backup_db_name = sys.argv[1]
    else:
        backup_db_name = default_backup_db
    
    print("=" * 60)
    print("Restore Data from Backup Database")
    print("=" * 60)
    print(f"Backup database: {backup_db_name}")
    print(f"Target database: {DB_NAME}")
    print()
    
    # Verify backup database exists
    print("Verifying backup database exists...")
    admin_conn = get_postgres_conn('postgres')
    admin_conn.autocommit = True
    with admin_conn.cursor() as cursor:
        cursor.execute("""
            SELECT 1 FROM pg_database WHERE datname = %s
        """, (backup_db_name,))
        if not cursor.fetchone():
            print(f"Error: Backup database '{backup_db_name}' does not exist!")
            print("\nAvailable backup databases:")
            cursor.execute("""
                SELECT datname 
                FROM pg_database 
                WHERE datname LIKE %s
                ORDER BY datname DESC
            """, (f"{DB_NAME}_backup_%",))
            backups = cursor.fetchall()
            if backups:
                for (backup,) in backups:
                    print(f"  - {backup}")
            else:
                print("  (none found)")
            sys.exit(1)
        print(f"Backup database '{backup_db_name}' found!")
    admin_conn.close()
    print()
    
    # Connect to both databases
    print("Connecting to databases...")
    backup_conn = get_postgres_conn(backup_db_name)
    target_conn = get_postgres_conn(DB_NAME)
    
    try:
        # Get tables from both databases
        print("Finding common tables...")
        backup_tables = set(get_tables(backup_conn))
        target_tables = set(get_tables(target_conn))
        common_tables = sorted(backup_tables & target_tables)
        
        print(f"Found {len(common_tables)} common tables")
        if not common_tables:
            print("No common tables found!")
            return
        
        # Start transaction and disable FK constraints
        print("\nStarting transaction and disabling FK constraints...")
        with target_conn.cursor() as cursor:
            # Disable triggers and FK checks (similar to SET session_replication_role = replica)
            cursor.execute("SET session_replication_role = replica")
        target_conn.commit()
        
        # Copy data for each table
        print("\nCopying data...")
        total_rows = 0
        
        for table_name in common_tables:
            # Get columns from both tables
            backup_columns = {col[0]: col[1] for col in get_columns(backup_conn, table_name)}
            target_columns = {col[0]: col[1] for col in get_columns(target_conn, table_name)}
            
            # Find common columns (preserve order from target)
            common_columns = []
            for col_name, col_type in get_columns(target_conn, table_name):
                if col_name in backup_columns:
                    common_columns.append((col_name, col_type))
            
            if not common_columns:
                print(f"  Skipping {table_name}: no common columns")
                continue
            
            # Copy data
            try:
                rows_inserted = copy_table_data(backup_conn, target_conn, table_name, common_columns)
                target_conn.commit()
                total_rows += rows_inserted
                print(f"  {table_name}: {rows_inserted} rows inserted")
            except Exception as e:
                print(f"  Error copying {table_name}: {e}")
                target_conn.rollback()
                # Continue with next table
        
        # Re-enable FK constraints
        print("\nRe-enabling FK constraints...")
        with target_conn.cursor() as cursor:
            cursor.execute("SET session_replication_role = origin")
        target_conn.commit()
        
        print()
        print("=" * 60)
        print(f"Data restoration complete! Total rows inserted: {total_rows}")
        print("=" * 60)
        
    except Exception as e:
        print(f"\nError during restoration: {e}")
        import traceback
        traceback.print_exc()
        target_conn.rollback()
        # Re-enable constraints even on error
        try:
            with target_conn.cursor() as cursor:
                cursor.execute("SET session_replication_role = origin")
            target_conn.commit()
        except:
            pass
        sys.exit(1)
    finally:
        backup_conn.close()
        target_conn.close()

if __name__ == '__main__':
    main()
